// IDs are numbers from postgres uuid generator (under the Kysely hood)
export type ID = string;

export interface Identifiable {
  id: ID;
}

// These get autogenerated on row creation
// Should add a trigger which bumps last updated on update
export interface Timestamps {
  created: Date;
  last_updated: Date;
}

export interface DbEntry extends Identifiable, Timestamps {}
